/* run_step5_check.sql
   Manual run of validate + publish, before the master proc exists.
   Run the parts one at a time and compare with the expected results. */

USE DATABASE SKYPOINTS_DB;

-- a quick way to see all five country tables together
CREATE OR REPLACE TEMPORARY VIEW V_COUNTRY_TABLES AS
          SELECT 'TABLE_USA'         AS TBL, MEMBER_ID, MEMBER_NAME, TIER_CODE, COUNTRY_CODE, STALE_MEMBER, LOAD_ID, INSERT_DATE, LAST_UPDATE_DATE FROM MAIN.TABLE_USA
UNION ALL SELECT 'TABLE_INDIA',       MEMBER_ID, MEMBER_NAME, TIER_CODE, COUNTRY_CODE, STALE_MEMBER, LOAD_ID, INSERT_DATE, LAST_UPDATE_DATE FROM MAIN.TABLE_INDIA
UNION ALL SELECT 'TABLE_PHILIPPINES', MEMBER_ID, MEMBER_NAME, TIER_CODE, COUNTRY_CODE, STALE_MEMBER, LOAD_ID, INSERT_DATE, LAST_UPDATE_DATE FROM MAIN.TABLE_PHILIPPINES
UNION ALL SELECT 'TABLE_CANADA',      MEMBER_ID, MEMBER_NAME, TIER_CODE, COUNTRY_CODE, STALE_MEMBER, LOAD_ID, INSERT_DATE, LAST_UPDATE_DATE FROM MAIN.TABLE_CANADA
UNION ALL SELECT 'TABLE_AUSTRALIA',   MEMBER_ID, MEMBER_NAME, TIER_CODE, COUNTRY_CODE, STALE_MEMBER, LOAD_ID, INSERT_DATE, LAST_UPDATE_DATE FROM MAIN.TABLE_AUSTRALIA;

/* ===== PART A: finish day 1 (the load from step 4, still in staging) ===== */
SET LID = (SELECT MAX(LOAD_ID) FROM CTRL.LOAD_CONTROL);
CALL MAIN.SP_VALIDATE_MEMBER($LID);   -- expect 0,0,0 and no error
CALL MAIN.SP_PUBLISH_MEMBER($LID);    -- expect INS 5, UPD 0, DEL 0
UPDATE CTRL.LOAD_CONTROL SET LOAD_STATUS = 'C', LOAD_ET = CURRENT_TIMESTAMP() WHERE LOAD_ID = $LID;

SELECT * FROM V_COUNTRY_TABLES ORDER BY TBL, MEMBER_ID;
-- expect: USA Elena, INDIA Ravi, PHILIPPINES Mateo, CANADA Nora, AUSTRALIA Jacob

/* ===== PART B: day 2 =====
   Upload data/test_scenarios/members_20240116_010000.txt to path: members */
INSERT INTO CTRL.LOAD_CONTROL (LOAD_STATUS, LOAD_ST) VALUES ('I', CURRENT_TIMESTAMP());
SET LID = (SELECT MAX(LOAD_ID) FROM CTRL.LOAD_CONTROL);

CALL RAW.SP_LOAD_RAW_MEMBER($LID);    -- expect INS 11
CALL STG.SP_LOAD_MEMBER($LID);        -- expect INS 11
CALL MAIN.SP_VALIDATE_MEMBER($LID);   -- no error; 2 WARN rows in the error log
CALL MAIN.SP_PUBLISH_MEMBER($LID);    -- expect INS 3 (Aiko, Lucas, Ravi into USA), UPD 1 (Elena), DEL 1 (Ravi out of India)
UPDATE CTRL.LOAD_CONTROL SET LOAD_STATUS = 'C', LOAD_ET = CURRENT_TIMESTAMP() WHERE LOAD_ID = $LID;

SELECT * FROM V_COUNTRY_TABLES ORDER BY TBL, MEMBER_ID;
-- expect: Ravi in TABLE_USA only (not INDIA), Elena PLT, Nora still LOAD_ID 1 (not rewritten),
--         Aiko in PHILIPPINES, Lucas in USA. Liam, Omar, Priya, Zara nowhere.

SELECT * FROM MAIN.MEMBER_COUNTRY_MOVE;                          -- expect Ravi IND -> USA
SELECT * FROM DQ.MEMBER_QUARANTINE WHERE LOAD_ID = $LID;          -- expect Priya, Omar, Zara, Liam x2
SELECT * FROM CTRL.PROCESS_ERROR_LOG WHERE LOAD_ID = $LID;        -- expect 2 WARN (reject rate, duplicates)

/* ===== PART C: late file =====
   Upload data/test_scenarios/members_20240114_230000.txt to path: members */
INSERT INTO CTRL.LOAD_CONTROL (LOAD_STATUS, LOAD_ST) VALUES ('I', CURRENT_TIMESTAMP());
SET LID = (SELECT MAX(LOAD_ID) FROM CTRL.LOAD_CONTROL);

CALL RAW.SP_LOAD_RAW_MEMBER($LID);    -- expect INS 1
CALL STG.SP_LOAD_MEMBER($LID);        -- expect INS 1
CALL MAIN.SP_VALIDATE_MEMBER($LID);
CALL MAIN.SP_PUBLISH_MEMBER($LID);    -- expect 0,0,0: older than what's published, ignored
UPDATE CTRL.LOAD_CONTROL SET LOAD_STATUS = 'C', LOAD_ET = CURRENT_TIMESTAMP() WHERE LOAD_ID = $LID;

SELECT MEMBER_ID, MEMBER_NAME, COUNTRY_CODE, FILE_TS FROM MAIN.MEMBER_CURRENT WHERE MEMBER_ID = '223458';
-- expect Ravi still USA, FILE_TS 2024-01-16 01:00
