/* run_step6_check.sql
   Manual run of the redemption load, before the master proc exists. */

USE DATABASE SKYPOINTS_DB;

/* ===== PART A: day 1 JSON (already in raw from step 4) ===== */
SET LID = (SELECT MAX(LOAD_ID) FROM RAW.REDEMPTION_FEED);
CALL MAIN.SP_LOAD_REDEMPTIONS($LID);          -- expect INS 2 (RX10091, RX10092)

SELECT * FROM MAIN.V_REDEMPTION_ENRICHED ORDER BY TXN_ID;
-- expect RX10091 COMPLETED 12000, RX10092 PENDING 5000, both Elena, IS_ORPHAN FALSE

/* ===== PART B: day 2 JSON =====
   Upload data/test_scenarios/redemptions_20240116.json to path: redemptions */
INSERT INTO CTRL.LOAD_CONTROL (LOAD_STATUS, LOAD_ST) VALUES ('I', CURRENT_TIMESTAMP());
SET LID = (SELECT MAX(LOAD_ID) FROM CTRL.LOAD_CONTROL);

CALL RAW.SP_LOAD_RAW_REDEMPTION($LID);        -- expect INS 3 (three documents)
CALL MAIN.SP_LOAD_REDEMPTIONS($LID);          -- expect INS 2 (RX10093, RX10094), UPD 1 (RX10092)
UPDATE CTRL.LOAD_CONTROL SET LOAD_STATUS = 'C', LOAD_ET = CURRENT_TIMESTAMP() WHERE LOAD_ID = $LID;

SELECT * FROM MAIN.V_REDEMPTION_ENRICHED ORDER BY TXN_ID;
-- expect RX10092 now COMPLETED, RX10093 -300 with NON_POSITIVE_MILES,
--        RX10094 member 999999 IS_ORPHAN TRUE

SELECT * FROM DQ.REDEMPTION_QUARANTINE WHERE LOAD_ID = $LID;
-- expect 1 row: member 223458, REDEMPTIONS_NOT_ARRAY

SELECT * FROM MAIN.V_MEMBER_REDEMPTION_SUMMARY WHERE MEMBER_ID = '223457';
-- expect Elena: COMPLETED_MILES 17000 (12000 + 5000), PENDING_TXNS 0
